2025-06-17 17:21:02,737 INFO    MainThread:55970 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_setup.py:_flush():68] Configure stats pid to 55970
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_setup.py:_flush():68] Loading settings from /Users/huiyufei/.config/wandb/settings
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_setup.py:_flush():68] Loading settings from /Users/huiyufei/Desktop/mini_audio_caption/wandb/settings
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_init.py:_log_setup():528] Logging user logs to /Users/huiyufei/Desktop/mini_audio_caption/wandb/run-20250617_172102-xtvqc555/logs/debug.log
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_init.py:_log_setup():529] Logging internal logs to /Users/huiyufei/Desktop/mini_audio_caption/wandb/run-20250617_172102-xtvqc555/logs/debug-internal.log
2025-06-17 17:21:02,738 INFO    MainThread:55970 [wandb_init.py:init():644] calling init triggers
2025-06-17 17:21:02,739 INFO    MainThread:55970 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2025-06-17 17:21:02,739 INFO    MainThread:55970 [wandb_init.py:init():680] starting backend
2025-06-17 17:21:02,739 INFO    MainThread:55970 [wandb_init.py:init():684] sending inform_init request
2025-06-17 17:21:02,856 INFO    MainThread:55970 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-06-17 17:21:02,856 INFO    MainThread:55970 [wandb_init.py:init():697] backend started and connected
2025-06-17 17:21:02,867 INFO    MainThread:55970 [wandb_init.py:init():790] updated telemetry
2025-06-17 17:21:02,892 INFO    MainThread:55970 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-06-17 17:21:02,897 WARNING MsgRouterThr:55970 [router.py:message_loop():75] message_loop has been closed
2025-06-17 17:21:12,943 ERROR   MainThread:55970 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/envs/audio_caption/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/opt/anaconda3/envs/audio_caption/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
  File "/opt/anaconda3/envs/audio_caption/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
